### ISSUE TITLE
Invalid flags supplied to RegExp constructor 'u'

### ISSUE THREAD

**Issue by vigneswaranm** [oozcitak/xmlbuilder-js#156]
We are getting the issue "Invalid flags supplied to RegExp constructor 'u'" in lib/XMLStringifier.js:140

in the below line
str.match(/[\u0000\ud800-\udfff\ufffe-\uffff]/u);

The /u modifier in PHP is for unicode support. This modifier is not supported in JavaScript.

**Comment by EDais** [comment]
Had the same issue here, updating to latest LTS version of node.js seemed to do the trick

**Comment by vigneswaranm** [comment]
i have tested in 4.2.2  version but still, it failed which version did you use

**Comment by EDais** [comment]
Still getting the error here on version 4.4.7, it's working on the current LTS version of 6.10.3

**Comment by oozcitak** [comment]
node.js 6.0 is required starting from xmlbuilder v9.

**Comment by ds82** [comment]
Please consider to support all node LTS versions as long as they are in maintenance. Humans are bad at semver. Dropping node4 support broke our builds, because another library author just depended on xmlbuilder >= 2 in her library. I know thats not your fault, but if important packages like yours would at least not drop support for active/in maintenance node LTS versions, it would make life a lot easier ..

**Comment by oozcitak** [comment]
Fair point. I'll se what I can do.

**Comment by formspoint** [comment]
Just upgraded and ran into this issue.  Please consider support for all LTS versions.

**Comment by tregagnon** [comment]
PR #161 should restore the compatibility.
