### ISSUE TITLE
Not possible to build a list of non-unique elements non-contiguously with JSON

### ISSUE THREAD

**Issue by jvonachen** [oozcitak/xmlbuilder-js#239]
I'm trying to create SVG documents.  SVGs are rendered in the order that the child elements are listed in a parent element.  This means that there are many examples where non-unique elements need to be listed in a specific order which is non-contiguous.  As far as I can see this isn't possible using a JSON object the current state the software is in.  Only contiguous lists of non-unique elements are possible.  Unless I am wrong.

**Comment by oozcitak** [comment]
It's actually possible, though not pretty:
```js
const builder = require('xmlbuilder');

const obj = {
  root: {
    '#text1': [
      { node: 'value1' },
      { node: 'value2' }
    ],
    '#comment': 'comment node',
    '#text2': [
      { node: 'value3' },
      { node: 'value4' }
    ]
  }
};

console.log(builder.create(obj).end({ pretty: true });

```
```xml
<?xml version="1.0"?>
<root>
  <node>value1</node>
  <node>value2</node>
  <!-- comment node -->
  <node>value3</node>
  <node>value4</node>
</root>
```
The `#text` decorator creates a text node from its value. However if its value is an object instead of a string, it passes it on to the `ele` function of its parent node; which has the side effect of creating nodes under parent. Above example uses this side effect to convert arrays of JS nodes under the parent `root` element.

***Note:*** `xmlbuilder` uses `startsWith` while matching decorators, so `#text1`, `#text2`, `#text_whatever` are all evaluated as `#text`. This is used here to create a JS object with multiple `#text` keys.
